# Generated by Django 5.0.6 on 2024-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_delete_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mini_descricao',
            field=models.TextField(max_length=400),
        ),
    ]
