# Generated by Django 5.0.6 on 2024-06-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_mini_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='imagem_destaque',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
