# Generated by Django 5.0.6 on 2024-06-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_imagem_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='imagem_solta',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
