# Generated by Django 5.0.6 on 2024-06-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_imagem_solta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='descricao_completa',
        ),
        migrations.AddField(
            model_name='game',
            name='descricao_parag1',
            field=models.TextField(default=0, max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='descricao_parag2',
            field=models.TextField(default='dada', max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='descricao_parag3',
            field=models.TextField(default='ewe', max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='descricao_parag4',
            field=models.TextField(default='dsdsd', max_length=700),
            preserve_default=False,
        ),
    ]
