# Generated by Django 5.0.6 on 2024-06-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_game_descricao_completa_game_descricao_parag1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='descricao_parag1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='descricao_parag2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='descricao_parag3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='descricao_parag4',
        ),
        migrations.AddField(
            model_name='game',
            name='descricao_completa',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
